package fr.zoumanatraore.restdemo.model;

// Generated 31 août 2012 17:55:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "abiyan")
@XmlRootElement
public class Tag implements java.io.Serializable {

	private String name;
	private String latitude;
	private String longitude;
	private String creationDate;
	private String lastUpdate;
	private String phone;
	private Set<Vote> votes = new HashSet<Vote>(0);
	private Set<Item> items = new HashSet<Item>(0);

	public Tag() {
	}

	public Tag(String name, String latitude, String longitude) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Tag(String name, String latitude, String longitude,
			String creationDate, String lastUpdate, String phone,
			Set<Vote> votes, Set<Item> items) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.phone = phone;
		this.votes = votes;
		this.items = items;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "latitude", nullable = false, length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "creationDate", length = 45)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "lastUpdate", length = 45)
	public String getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(String lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<Vote> getVotes() {
		return this.votes;
	}

	public void setVotes(Set<Vote> votes) {
		this.votes = votes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
