package fr.zoumanatraore.restdemo.model;

// Generated 31 août 2012 17:55:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Vote generated by hbm2java
 */
@Entity
@Table(name = "vote", catalog = "abiyan")
@XmlRootElement
public class Vote implements java.io.Serializable {

	private int id;
	private Tag tag;
	private Integer plus;
	private Integer minus;

	public Vote() {
	}

	public Vote(int id) {
		this.id = id;
	}

	public Vote(int id, Tag tag, Integer plus, Integer minus) {
		this.id = id;
		this.tag = tag;
		this.plus = plus;
		this.minus = minus;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag")
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@Column(name = "plus")
	public Integer getPlus() {
		return this.plus;
	}

	public void setPlus(Integer plus) {
		this.plus = plus;
	}

	@Column(name = "minus")
	public Integer getMinus() {
		return this.minus;
	}

	public void setMinus(Integer minus) {
		this.minus = minus;
	}

}
